### ISSUE TITLE
lottieconv documentation not available

### ISSUE THREAD

**Issue by LuckyTurtleDev** [msrd0/rlottie-rs#12]
The documentation of the lottieconv release is not available at https://docs.msrd0.de

**Comment by msrd0** [comment]
Yes, there is a delay of about a day after publishing on crates.io. They are available now: https://docs.msrd0.de/lottieconv/0.1.0/lottieconv/index.html

Also, you might want to look at https://github.com/msrd0/rlottie-rs/blob/lottieconv-0.1.0/lottieconv/bin/lottie2gif.rs#L63 for an example how to use the crate.
