### ISSUE TITLE
Any plans to use gifski instead of gif crates?

### ISSUE THREAD

**Issue by yisibl** [msrd0/rlottie-rs#4]
Thanks for creating this great project. Is there a plan to replace gif crates with [gifski](https://crates.io/crates/gifski) in this project? As far as I know, gifski generates better quality GIF files.

Then I don't know if there is a performance difference between the two.

**Comment by msrd0** [comment]
There are no plans to change that library as I haven't yet encountered any problems with the gif crate. Also, gifski uses a very restrictive license (AGPL) which I would like to avoid for libraries.

Is there a particular reason you prefer gifski over the gif crate?

**Comment by yisibl** [comment]
Licensing is indeed an issue, not for any particular reason that I can think of, but I'm just curious if gifski will result in a performance or quality improvement.

Our usage scenario is mainly server-side, where users generate GIFs or MP4s when uploading multiple lottie JSON files in bulk, so it would be important to be able to multi-thread or use GPU to accelerate.

**Comment by msrd0** [comment]
Performance wise there's a lot the gif crate can do - if you chose the optimal color preserve quality it is unbereably slow, and you can then set some number to "trade" color accuracy for performance. I just chose some value that was reasonably fast and where I couldn't see quality problems with some sample files - if you want to spend the time fine-tuning this value, feel free to let me know if you find a better one.

**Comment by msrd0** [comment]
So to summarize above - I'm not going to add gifski support unless someone finds a big problem with the existing gif crate, which doesn't seem to be the case.
