### ISSUE TITLE
Support conversion to videos

### ISSUE THREAD

**Issue by yisibl** [msrd0/rlottie-rs#5]
Support for converting to video will be very useful, as it is smaller than GIF files and can take advantage of GPU hardware acceleration when playing.

There is a [SkottieTool](https://github.com/google/skia/blob/main/modules/skottie/src/SkottieTool.cpp) in Skottie that generates mp4 files from FFmpeg, I don't know if this is something I could learn from.

If you plan to support video, I can port this library to Node.js via [napi-rs](https://github.com/napi-rs/napi-rs/).

**Comment by msrd0** [comment]
I'm not going to add nor maintain any code other than what is necessary to convert lottie files to gif files. Feel free to use the rlottie crate and build your own conversion library with it.

**Comment by yisibl** [comment]
Thanks!
