### ISSUE TITLE
Render to arbitary size surface.

### ISSUE THREAD

**Issue by cireu** [msrd0/rlottie-rs#8]
lottie is a vector image format and it can be render to arbitary size surface losslessly. But `Animation::render()` requires a `Size` struct which can't be constructed. Only `Animation::size()` can return a `Size` struct.

What about add a constructor function to `Size` struct?

**Comment by cireu** [comment]
Thoughts: Can we model a `Surface` struct(like the C++ class defined in `rlottie.h`) and make `Animation::render` render on it?

```rust
struct Surface {
  bytes: Vec<BGRA8>,
  width: u64,
  height: u64,
}
```

**Comment by msrd0** [comment]
The `Size` struct was made private because it used `size_t` which was a different type depending on the target architecture. However, I found an option to just make bindgen use `usize` so it can be made public again.

Also, a `Surface` struct sounds like a good idea.
